# 1. On part d'une image Nginx légère
FROM nginx:alpine

# 2. On copie ta configuration Nginx personnalisée (très important pour le reverse proxy vers le back)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 3. On copie tes fichiers statiques (HTML, JS) dans le dossier par défaut de Nginx
COPY public /usr/share/nginx/html

# 4. Nginx écoute par défaut sur le port 80
EXPOSE 80